baseURL = ''
languageCode = 'en-us'
title = 'Nidio Dolfini'

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[params]
# readMore = true
fullPostContent = true
singleDateFormat = "Mon, Jan 2, 2006"
title = "I'm Nidio Dolfini"
author = "Nidio Dolfini"
description = "You don't start out writing good stuff."
profilePicture = "images/nidio.jpg"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/nidiodolfini"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/nidiodolfini"

[[params.socialIcons]]
icon = "fab fa-dev"
title = "DEV"
url = "https://dev.to/nidio"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "nidio@dolfini.dev"
url = "mailto:nidio@dolfini.dev"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"