baseurl = "https://dolfini.dev/"
languageCode = "pt-br"
theme = "hugo-theme-terminal"

pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true


[params]
  title = "Nidio Dolfini"
  contentTypeName = "posts"
  fullWidthTheme = false
  centerTheme = false
  ReadMore = "Leia mais..." # A variável correta no lugar certo
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/nidiodolfini"
    icon = "fab fa-github"  # Caminho para o ícone na pasta /static

  [[params.social]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/nidiodolfini/"
    icon = "fab fa-linkedin"

  [[params.social]]
    name = "DEV"
    url = "https://dev.to/nidio"
    icon = "fab fa-dev"

  [[params.social]]
    name = "Email"
    url = "mailto:nidio@dolfini.dev"
    icon = "fas fa-envelope"

[languages]
  [languages.en]
    title = "Nidio"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "nidio@cloud:~$"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "Sobre"
        url = "/about"
      
